// import React, { useEffect, useState } from 'react';

// import { Card, FormField, Loader } from '../components';

// const RenderCards = ({ data, title }) => {
//   if (data?.length > 0) {
//     return (
//       data.map((post) => <Card key={post._id} {...post} />)
//     );
//   }

//   return (
//     <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase">{title}</h2>
//   );
// };

// const Home = () => {
//   const [loading, setLoading] = useState(false);
//  const [allPosts, setAllPosts] = useState([]);

//   const [searchText, setSearchText] = useState('');
//   const [searchTimeout, setSearchTimeout] = useState(null);
//   const [searchedResults, setSearchedResults] = useState([]);

//   const fetchPosts = async () => {
//     setLoading(true);

//     try {
//       const response = await fetch(
//   'http://localhost:8080/api/v1/post', {
//         method: 'GET',
//         headers: {
//           'Content-Type': 'application/json',
//         },
//       });

//       if (response.ok) {
//         const result = await response.json();
//         setAllPosts(result.data.reverse());
//       }
//     } catch (err) {
//       alert(err);
//     } finally {
//       setLoading(false);
//     }
//   };

//   useEffect(() => {
//     fetchPosts();
//   }, []);

//   const handleSearchChange = (e) => {
//   clearTimeout(searchTimeout);

//   const value = e.target.value;
//   setSearchText(value);

//   setSearchTimeout(
//     setTimeout(() => {
//       const searchResult = (allPosts || []).filter((item) =>
//         item.name.toLowerCase().includes(value.toLowerCase()) ||
//         item.prompt.toLowerCase().includes(value.toLowerCase())
//       );

//       setSearchedResults(searchResult);
//     }, 500)
//   );
// };
//   return (
//     <section className="max-w-7xl mx-auto">
//       <div>
//         <h1 className="font-extrabold text-[#222328] text-[32px]">The Community Showcase</h1>
//         <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
//       </div>

//       <div className="mt-16">
//         <FormField
//           labelName="Search posts"
//           type="text"
//           name="text"
//           placeholder="Search something..."
//           value={searchText}
//           handleChange={handleSearchChange}
//         />
//       </div>

//       <div className="mt-10">
//         {loading ? (
//           <div className="flex justify-center items-center">
//             <Loader />
//           </div>
//         ) : (
//           <>
//             {searchText && (
//               <h2 className="font-medium text-[#666e75] text-xl mb-3">
//                 Showing Resuls for <span className="text-[#222328]">{searchText}</span>:
//               </h2>
//             )}
//             <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
//               {searchText ? (
//                 <RenderCards
//                   data={searchedResults}
//                   title="No Search Results Found"
//                 />
//               ) : (
//                 <RenderCards
//                   data={allPosts}
//                   title="No Posts Yet"
//                 />
//               )}
//             </div>
//           </>
//         )}
//       </div>
//     </section>
//   );
// };

// export default Home;

import React, { useState } from "react";
import { Link, useNavigate } from "react-router-dom";

import {
  ArrowRight,
  Sparkles,
  Wand2,
  Image as ImageIcon,
  Zap,
  Heart,
  History,
  Search,
  Share2,
  Download,
  ChevronDown,
  Play,
  Palette,
  Users,
  CheckCircle,
} from "lucide-react";

import "./Home.css";


/* =========================================================
   FEATURES
========================================================= */

const features = [
  {
    icon: Wand2,
    title: "AI Image Generation",
    description:
      "Transform your text prompts into unique, high-quality images using AI-powered generation.",
    path: "/create-post",
    protected: true,
  },
  {
    icon: ImageIcon,
    title: "Creative Gallery",
    description:
      "Explore creative artwork, discover new ideas, and get inspired by AI-generated creations.",
    path: "/gallery",
    protected: true,
  },
  {
    icon: Heart,
    title: "Save Favorites",
    description:
      "Save the images you love and keep your favorite AI creations organized in one place.",
    path: "/favorites",
    protected: true,
  },
  {
    icon: History,
    title: "Generation History",
    description:
      "Keep track of your previous generations and revisit your creative journey anytime.",
    path: "/history",
    protected: true,
  },
  {
    icon: Search,
    title: "Explore Creations",
    description:
      "Discover different styles, concepts, and creative possibilities generated by the community.",
    path: "/gallery",
    protected: true,
  },
  {
    icon: Share2,
    title: "Share Your Art",
    description:
      "Share your AI-generated artwork and inspire other creators with your imagination.",
    path: "/gallery",
    protected: true,
  },
];


/* =========================================================
   CREATION TYPES
========================================================= */

const creationTypes = [
  {
    icon: "🎨",
    title: "Digital Art",
    description: "Create unique artistic illustrations.",
  },
  {
    icon: "🏙️",
    title: "Creative Scenes",
    description: "Build amazing environments and worlds.",
  },
  {
    icon: "👤",
    title: "Characters",
    description: "Generate unique characters and portraits.",
  },
  {
    icon: "🚀",
    title: "Sci-Fi",
    description: "Imagine futuristic worlds and technology.",
  },
  {
    icon: "🧚",
    title: "Fantasy",
    description: "Bring magical worlds to life.",
  },
  {
    icon: "📸",
    title: "Realistic",
    description: "Generate realistic visual concepts.",
  },
];


/* =========================================================
   SHOWCASE IMAGES
========================================================= */

const showcaseImages = [
  {
    image: "/src/assets/showcase1.png",
    title: "Futuristic City",
    category: "Sci-Fi",
  },
  {
    image: "/src/assets/showcase2.png",
    title: "Fantasy World",
    category: "Fantasy",
  },
  {
    image: "/src/assets/showcase3.png",
    title: "Digital Portrait",
    category: "Portrait",
  },
  {
    image: "/src/assets/showcase4.png",
    title: "Dream Landscape",
    category: "Nature",
  },
];


/* =========================================================
   EXAMPLE PROMPTS
========================================================= */

const examplePrompts = [
  "A futuristic city floating above the clouds at sunset",
  "A magical forest with glowing flowers and fireflies",
  "A cyberpunk warrior standing in a neon city",
  "A peaceful mountain landscape under a starry night",
];


/* =========================================================
   HOME COMPONENT
========================================================= */

const Home = () => {
  const navigate = useNavigate();

  const [prompt, setPrompt] = useState(examplePrompts[0]);

  const [isGenerating, setIsGenerating] = useState(false);

  const [generated, setGenerated] = useState(false);


  /* =======================================================
     CHECK LOGIN STATUS
  ======================================================= */

  const isLoggedIn = () => {
    return Boolean(
      localStorage.getItem("token") ||
      localStorage.getItem("user") ||
      localStorage.getItem("userId")
    );
  };


  /* =======================================================
     PROTECTED NAVIGATION
  ======================================================= */

  const handleProtectedNavigation = (path) => {
    if (isLoggedIn()) {
      navigate(path);
      return;
    }

    navigate("/login", {
      state: {
        redirectTo: path,
      },
    });
  };


  /* =======================================================
     START CREATING
  ======================================================= */

  const handleStartCreating = () => {
    handleProtectedNavigation("/create-post");
  };


  /* =======================================================
     EXPLORE GALLERY
  ======================================================= */

  const handleExploreGallery = () => {
    handleProtectedNavigation("/gallery");
  };


  /* =======================================================
     FEATURE CLICK
  ======================================================= */

  const handleFeatureClick = (feature) => {
    if (feature.protected) {
      handleProtectedNavigation(feature.path);
    } else {
      navigate(feature.path);
    }
  };


  /* =======================================================
     GENERATE DEMO
  ======================================================= */

  const handleGenerate = () => {
    if (!prompt.trim()) return;

    setIsGenerating(true);
    setGenerated(false);

    setTimeout(() => {
      setIsGenerating(false);
      setGenerated(true);
    }, 1800);
  };


  /* =======================================================
     RENDER
  ======================================================= */

  return (
    <div className="gencanvas-home">


      {/* =====================================================
          BACKGROUND EFFECTS
      ====================================================== */}

      <div className="background-effects">

        <div className="gradient-orb orb-one"></div>

        <div className="gradient-orb orb-two"></div>

        <div className="gradient-orb orb-three"></div>

        <div className="grid-background"></div>

      </div>


      {/* =====================================================
          NAVBAR
      ====================================================== */}

      <header className="landing-navbar">

        <div className="navbar-inner">


          {/* LOGO */}

          <Link
            to="/"
            className="brand"
          >

            <div className="brand-icon">

              <Sparkles size={19} />

            </div>

            <span>
              GenCanvasAI
            </span>

          </Link>


          {/* NAVIGATION */}

          <nav className="landing-nav-links">

            <a href="#home">
              Home
            </a>

            <a href="#explore">
              Explore
            </a>

            <a href="#about">
              About
            </a>

            <a href="#features">
              Features
            </a>

          </nav>


          {/* AUTH BUTTONS */}

          <div className="navbar-actions">

            <Link
              to="/login"
              className="nav-login"
            >
              Login
            </Link>

            <Link
              to="/signup"
              className="nav-signup"
            >
              Sign Up
            </Link>

          </div>

        </div>

      </header>


      {/* =====================================================
          HERO SECTION
      ====================================================== */}

      <section
        className="hero-section"
        id="home"
      >

        <div className="hero-content">


          <div className="hero-badge">

            <Sparkles size={16} />

            <span>
              AI-Powered Creative Platform
            </span>

          </div>


          <h1>

            Turn Your Imagination

            <span>
              {" "}Into Stunning Images
            </span>

          </h1>


          <p className="hero-description">

            GenCanvasAI transforms your ideas into visually
            stunning AI-generated artwork. Simply describe
            what you imagine, and let artificial intelligence
            bring your creativity to life.

          </p>


          {/* HERO BUTTONS */}

          <div className="hero-buttons">


            {/* START CREATING */}

            <button
              onClick={handleStartCreating}
              className="primary-button"
            >

              <Sparkles size={18} />

              Start Creating

              <ArrowRight size={18} />

            </button>


            {/* EXPLORE GALLERY */}

            <button
              onClick={handleExploreGallery}
              className="secondary-button"
            >

              <Play size={17} />

              Explore Gallery

            </button>


          </div>


          <div className="hero-trust">

            <CheckCircle size={16} />

            <span>
              Create • Explore • Save • Share
            </span>

          </div>

        </div>


        {/* =====================================================
            HERO VISUAL
        ====================================================== */}

        <div className="hero-visual">

          <div className="hero-glow"></div>


          <div className="ai-preview-card">


            <div className="preview-header">

              <div className="preview-dots">

                <span></span>

                <span></span>

                <span></span>

              </div>

              <span>
                GenCanvasAI
              </span>

              <Sparkles size={16} />

            </div>


            <div className="preview-image">

              <img
                src="/src/assets/preview.png"
                alt="GenCanvasAI AI generated artwork"
              />


              <div className="image-overlay">

                <Sparkles size={20} />

                <span>
                  AI Generated
                </span>

              </div>

            </div>


            <div className="preview-prompt">

              <div>

                <span>
                  Prompt
                </span>

                <p>
                  A futuristic city floating above
                  the clouds...
                </p>

              </div>


              <button
                onClick={handleStartCreating}
              >
                <ArrowRight size={17} />
              </button>

            </div>

          </div>


          {/* FLOATING CARD 1 */}

          <div className="floating-info-card card-one">

            <div className="floating-icon">

              <Sparkles size={18} />

            </div>

            <div>

              <strong>
                AI Creation
              </strong>

              <span>
                Generating artwork...
              </span>

            </div>

          </div>


          {/* FLOATING CARD 2 */}

          <div className="floating-info-card card-two">

            <div className="floating-icon">

              <Heart size={18} />

            </div>

            <div>

              <strong>
                Creative Gallery
              </strong>

              <span>
                Explore creations
              </span>

            </div>

          </div>

        </div>

      </section>


      {/* =====================================================
          SCROLL INDICATOR
      ====================================================== */}

      <a
        href="#about"
        className="scroll-indicator"
      >

        <span>
          Discover GenCanvasAI
        </span>

        <ChevronDown size={18} />

      </a>


      {/* =====================================================
          ABOUT SECTION
      ====================================================== */}

      <section
        className="about-section section-container"
        id="about"
      >

        <div className="about-content">

          <div className="section-badge">

            <Sparkles size={15} />

            About GenCanvasAI

          </div>


          <h2>

            Your imagination is

            <span>
              {" "}the starting point.
            </span>

          </h2>


          <p>

            GenCanvasAI is an AI-powered image generation
            platform designed to make digital creativity
            simple and accessible.

            Whether you are a designer, developer, content
            creator, student, or simply someone with an idea,
            GenCanvasAI helps transform your imagination into
            unique visual creations.

          </p>


          <p>

            Instead of spending hours designing an image
            from scratch, simply describe what you want.
            GenCanvasAI uses AI to transform your description
            into artwork that you can explore, save, revisit,
            and share.

          </p>


          <div className="about-stats">

            <div>

              <strong>
                AI
              </strong>

              <span>
                Powered Creation
              </span>

            </div>


            <div>

              <strong>
                ∞
              </strong>

              <span>
                Creative Possibilities
              </span>

            </div>


            <div>

              <strong>
                1
              </strong>

              <span>
                Simple Prompt
              </span>

            </div>

          </div>

        </div>


        <div className="about-visual">

          <div className="about-card">

            <div className="about-card-icon">

              <Wand2 size={28} />

            </div>


            <h3>

              From Words

              <span>
                {" "}To Visuals
              </span>

            </h3>


            <p>

              Your words become the foundation for
              something visually extraordinary.

            </p>


            <div className="about-flow">


              <div>

                <Sparkles size={20} />

                <span>
                  Your Idea
                </span>

              </div>


              <ArrowRight size={20} />


              <div>

                <Wand2 size={20} />

                <span>
                  AI
                </span>

              </div>


              <ArrowRight size={20} />


              <div>

                <ImageIcon size={20} />

                <span>
                  Artwork
                </span>

              </div>


            </div>

          </div>

        </div>

      </section>


      {/* =====================================================
          WHAT CAN YOU CREATE
      ====================================================== */}

      <section
        className="creation-section section-container"
        id="explore"
      >

        <div className="section-heading">

          <div className="section-badge">

            <Palette size={15} />

            Creative Possibilities

          </div>


          <h2>

            What can you

            <span>
              {" "}create?
            </span>

          </h2>


          <p>

            Explore different creative directions and
            transform your ideas into unique AI-generated
            visuals.

          </p>

        </div>


        <div className="creation-grid">

          {creationTypes.map((item) => (

            <button
              className="creation-card"
              key={item.title}
              onClick={handleStartCreating}
            >

              <div className="creation-emoji">
                {item.icon}
              </div>


              <h3>
                {item.title}
              </h3>


              <p>
                {item.description}
              </p>


              <ArrowRight size={17} />

            </button>

          ))}

        </div>

      </section>


      {/* =====================================================
          FEATURES
      ====================================================== */}

      <section
        className="features-section section-container"
        id="features"
      >

        <div className="section-heading">

          <div className="section-badge">

            <Zap size={15} />

            Powerful Features

          </div>


          <h2>

            Everything you need to

            <span>
              {" "}create.
            </span>

          </h2>


          <p>

            GenCanvasAI gives you a complete creative
            environment for generating, exploring,
            organizing, and sharing artwork.

          </p>

        </div>


        <div className="features-grid">

          {features.map((feature) => {

            const Icon = feature.icon;

            return (

              <button
                className="feature-card"
                key={feature.title}
                onClick={() =>
                  handleFeatureClick(feature)
                }
              >

                <div className="feature-icon">

                  <Icon size={23} />

                </div>


                <h3>
                  {feature.title}
                </h3>


                <p>
                  {feature.description}
                </p>


                <div className="feature-link">

                  Explore

                  <ArrowRight size={16} />

                </div>

              </button>

            );

          })}

        </div>

      </section>


      {/* =====================================================
          HOW IT WORKS
      ====================================================== */}

      <section
        className="steps-section section-container"
      >

        <div className="section-heading">

          <div className="section-badge">

            <Wand2 size={15} />

            Simple Process

          </div>


          <h2>

            From idea to image in

            <span>
              {" "}three steps.
            </span>

          </h2>

        </div>


        <div className="steps-container">


          <div className="step-item">

            <div className="step-number">
              01
            </div>

            <Sparkles size={27} />

            <h3>
              Describe Your Idea
            </h3>

            <p>

              Write a simple description of the
              image you want GenCanvasAI to create.

            </p>

          </div>


          <div className="step-line"></div>


          <div className="step-item">

            <div className="step-number">
              02
            </div>

            <Wand2 size={27} />

            <h3>
              Generate With AI
            </h3>

            <p>

              Our AI processes your prompt and
              transforms your description into
              visual artwork.

            </p>

          </div>


          <div className="step-line"></div>


          <div className="step-item">

            <div className="step-number">
              03
            </div>

            <Heart size={27} />

            <h3>
              Save & Share
            </h3>

            <p>

              Save your favorite creations,
              download them, and share your
              artwork with others.

            </p>

          </div>

        </div>

      </section>


      {/* =====================================================
          INTERACTIVE AI DEMO
      ====================================================== */}

      <section
        className="demo-section section-container"
      >

        <div className="demo-heading">

          <div className="section-badge">

            <Sparkles size={15} />

            Try GenCanvasAI

          </div>


          <h2>

            See your idea

            <span>
              {" "}come to life.
            </span>

          </h2>


          <p>

            Try an example prompt and experience how
            GenCanvasAI transforms words into visual
            concepts.

          </p>

        </div>


        <div className="demo-container">


          <div className="demo-controls">

            <label>
              Describe your image
            </label>


            <textarea
              value={prompt}
              onChange={(e) =>
                setPrompt(e.target.value)
              }
              placeholder="Describe the image you want..."
              rows={5}
            />


            <div className="prompt-examples">

              <span>
                Try:
              </span>


              {examplePrompts.map((example) => (

                <button
                  key={example}
                  onClick={() =>
                    setPrompt(example)
                  }
                >
                  {example.slice(0, 28)}...
                </button>

              ))}

            </div>


            <button
              className="generate-demo-button"
              onClick={handleGenerate}
              disabled={isGenerating}
            >

              {isGenerating ? (

                <>

                  <span className="loading-spinner"></span>

                  Generating...

                </>

              ) : (

                <>

                  <Sparkles size={18} />

                  Generate Image

                </>

              )}

            </button>

          </div>


          <div className="demo-preview">


            {!generated && !isGenerating && (

              <div className="demo-placeholder">

                <div className="demo-placeholder-icon">

                  <ImageIcon size={35} />

                </div>


                <h3>
                  Your creation will appear here
                </h3>


                <p>

                  Enter a prompt and click
                  Generate Image to see the magic.

                </p>

              </div>

            )}


            {isGenerating && (

              <div className="generating-state">

                <div className="generation-animation">

                  <Sparkles size={40} />

                </div>


                <h3>
                  Creating your artwork...
                </h3>


                <p>

                  GenCanvasAI is transforming
                  your idea.

                </p>

              </div>

            )}


            {generated && !isGenerating && (

              <div className="generated-demo">

                <img
                  src="/src/assets/preview.png"
                  alt="Generated AI artwork"
                />


                <div className="generated-overlay">

                  <span>
                    AI Generated Preview
                  </span>


                  <div>


                    <button
                      onClick={() =>
                        handleProtectedNavigation(
                          "/favorites"
                        )
                      }
                      title="Save to favorites"
                    >

                      <Heart size={17} />

                    </button>


                    <button
                      onClick={() =>
                        handleProtectedNavigation(
                          "/create-post"
                        )
                      }
                      title="Create your own"
                    >

                      <Download size={17} />

                    </button>


                    <button
                      onClick={() =>
                        handleProtectedNavigation(
                          "/gallery"
                        )
                      }
                      title="Explore gallery"
                    >

                      <Share2 size={17} />

                    </button>


                  </div>

                </div>

              </div>

            )}

          </div>

        </div>

      </section>


      {/* =====================================================
          CREATIVE SHOWCASE
      ====================================================== */}

      <section
        className="showcase-section section-container"
      >

        <div className="section-heading">

          <div className="section-badge">

            <ImageIcon size={15} />

            Creative Showcase

          </div>


          <h2>

            Imagine it.

            <span>
              {" "}Create it.
            </span>

          </h2>


          <p>

            Explore the possibilities of AI-generated
            creativity.

          </p>

        </div>


        <div className="showcase-grid">

          {showcaseImages.map((item) => (

            <div
              className="showcase-card"
              key={item.title}
            >

              <img
                src={item.image}
                alt={item.title}
              />


              <div className="showcase-overlay">

                <div>

                  <span>
                    {item.category}
                  </span>

                  <h3>
                    {item.title}
                  </h3>

                </div>


                <button
                  onClick={handleExploreGallery}
                  title="Explore gallery"
                >

                  <ArrowRight size={18} />

                </button>

              </div>

            </div>

          ))}

        </div>


        {/* PROTECTED GALLERY BUTTON */}

        <button
          onClick={handleExploreGallery}
          className="showcase-button"
        >

          Explore Full Gallery

          <ArrowRight size={18} />

        </button>

      </section>


      {/* =====================================================
          CTA
      ====================================================== */}

      <section className="cta-section">

        <div className="cta-background"></div>


        <div className="cta-content">

          <div className="cta-icon">

            <Sparkles size={30} />

          </div>


          <h2>

            Your imagination.

            <span>
              {" "}Your creation.
            </span>

          </h2>


          <p>

            Start creating unique AI-generated
            artwork with GenCanvasAI today.

          </p>


          <button
            onClick={handleStartCreating}
            className="cta-button"
          >

            Start Creating

            <ArrowRight size={19} />

          </button>


          <div className="cta-login">

            Already have an account?

            <Link to="/login">
              Login
            </Link>

          </div>

        </div>

      </section>


      {/* =====================================================
          FOOTER
      ====================================================== */}

      <footer className="landing-footer">


        <div className="footer-main">


          <div className="footer-brand">

            <Link
              to="/"
              className="brand"
            >

              <div className="brand-icon">

                <Sparkles size={18} />

              </div>

              <span>
                GenCanvasAI
              </span>

            </Link>


            <p>

              Transform your imagination into
              stunning AI-generated artwork.

            </p>

          </div>


          <div className="footer-column">

            <h4>
              Explore
            </h4>

            <a href="#about">
              About
            </a>

            <a href="#features">
              Features
            </a>

            <a href="#explore">
              Explore
            </a>

            <button
              onClick={handleExploreGallery}
            >
              Gallery
            </button>

          </div>


          <div className="footer-column">

            <h4>
              Account
            </h4>

            <Link to="/login">
              Login
            </Link>

            <Link to="/signup">
              Sign Up
            </Link>

            <Link to="/profile">
              Profile
            </Link>

          </div>

        </div>


        <div className="footer-bottom">

          <span>

            © {new Date().getFullYear()}
            {" "}GenCanvasAI

          </span>


          <span>

            Create. Imagine. Inspire.

          </span>

        </div>

      </footer>

    </div>
  );
};


export default Home;
